# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "vmd"
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "usbcore.autosuspend=-1" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cc8b9b29-993e-4956-92ad-27f6e08ef2df";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0EE5-AA2F";
    fsType = "vfat";
  };

  fileSystems."/run/media/hkaz0" = {
    device = "/dev/disk/by-uuid/1C4840A148407B90";
    fsType = "ntfs-3g";
    options = [
      "nofail"
      "uid=1000"
      "gid=100"
      "dmask=007"
      "fmask=117"
      "user"
      "u+rwx"
      "g+rwx"
      "o+rwx"
      "users"
      "a+rwx"
      "exec"
      "umask=000"
    ];
  };
  fileSystems."/mnt/c" = {
    device = "/dev/disk/by-uuid/a3d31b70-c6be-43ee-a470-7a77d471ed45";
    fsType = "auto";
    # options = ["nofail" "uid=1000" "gid=100" "user"];
    # options = ["nofail" "uid=1000" "gid=100" "dmask=007" "fmask=117" "user" "u+rwx" "g+rwx" "o+rwx" "users" "a+rwx" "exec" "umask=000"];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
